2020-01-05 22:58:20

diff --git a/gitpush b/gitpush
--- a/gitpush
+++ b/gitpush
@@ -1,6 +1,11 @@
-#!/bin/bash -e
+#!/bin/zsh -e
 
+# check
 ! git status &> /dev/null && echo "请在项目文件夹中执行脚本！" && exit 1
+if [ -z "${GIT_USER_NAME}" -o -z "${GIT_USER_EMAIL}" ]; then
+	echo "GIT_USER_NAME and GIT_USER_EMAIL is required!"
+	exit 1
+fi
 # git远程地址
 git_remote_url=$(git remote -v | grep "(push)" | head -1 | awk '{print $2}')
 # 项目名称
@@ -8,8 +13,8 @@ project_name=$(echo "$git_remote_url" | awk -F '/' '{print$NF}' | sed -e 's/.git
 # 清除系统自动生产的文件
 find . -name '.DS_Store' | xargs rm -rf
 # init user
-git config user.name monlor
-git config user.email monlor@qq.com
+git config user.name ${GIT_USER_NAME}
+git config user.email ${GIT_USER_EMAIL}
 # begin to push
 echo "Push [${project_name}] To [${git_remote_url}]."
 git commit -a -m "`date "+%Y-%m-%d %H:%M:%S"`"
